Models/DocUpload.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevDemo.Models
{
    public class DocUpload
    {
        public Guid DocUploadId { get; set; }
        public string FileName { get; set; }
        public Guid UserInfoId { get; set; }
        public UserInfo UserInfo { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace DevDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DevDemo.Models
{
    public class UserInfo
    {
        public Guid UserInfoId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public long TransNumber { get; set; }
        public DateTimeOffset Date { get; set; } 
        public virtual ICollection<DocUpload> fileUploads { get; set; }
    }
}

ViewModels/UserInfoViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DevDemo.ViewModels
{
    public class UserInfoViewModel
    {
        [Required,Display(Name = "Full Name", Prompt = "Enter Full Name")]
        public string Name { get; set; }
        [Required,Display(Name = "Email", Prompt = "Enter Email"), DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        
        [Required,DataType(DataType.MultilineText),Display(Name = "Address", Prompt = "Enter Address")]    
        public string Address { get; set; }    
        [Required,Display(Name = "Upload Documents"), DataType(DataType.Upload)]
        public List<IFormFile> UserFiles { get; set; }
        public Guid UserInfoId { get; set; }
       
    }
}

ViewModels/UserSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevDemo.ViewModels
{
    public class UserSearchViewModel
    {
        public string email { get; set; }
        public long TransNum { get; set; }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DevDemo.Models;

namespace DevDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UserInfoController.cs
using DevDemo.Data;
using DevDemo.Models;
using DevDemo.Services;
using DevDemo.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Internal;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DevDemo.Controllers
{
    public class UserInfoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IUnitOfWork _unitOfWork;
        public UserInfoController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, IUnitOfWork unitOfWork)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _unitOfWork = unitOfWork;
        }
        public IActionResult UserUpload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UserUpload(UserInfoViewModel Vmodel)
        {
            if (ModelState.IsValid)
            {  
                UserInfo user = new UserInfo()
                {   UserInfoId = Vmodel.UserInfoId,
                    Name = Vmodel.Name,
                    Email = Vmodel.Email,
                    Address = Vmodel.Address,
                    TransNumber = _unitOfWork.GetTransactionNum(),
                    Date = DateTimeOffset.Now
                };
                _context.userInfo.Add(user);
                string webrootPath = _hostEnvironment.WebRootPath;
                var files = Vmodel.UserFiles;
                var uploads = Path.Combine(webrootPath, "images");

                for (int i = 0; i < files.Count; i++)
                {
                    string fileName = Vmodel.Name + files[i].FileName;
                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                    {
                        files[i].CopyTo(fileStreams);
                    }
                    var uploadFile = new DocUpload
                    {     
                        UserInfoId = user.UserInfoId,
                        FileName =  fileName
                    };
                    _context.docUploads.Add(uploadFile); 
                }
                await _context.SaveChangesAsync();
                if (_context.SaveChangesAsync().IsCompleted)
                {
                    _unitOfWork.MailSender(Vmodel.Name, Vmodel.Email, files, user.TransNumber);
                    TempData["Message"] = "File successfully uploaded";

                    return RedirectToAction("GetUser");

                }        
               
            }
            return View();
        }

        [HttpGet]
        public IActionResult GetUser()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetUser(UserSearchViewModel Vmodel)
        {
            if (ModelState.IsValid)
            {

                var user = _unitOfWork.GetUser(Vmodel.TransNum, Vmodel.email); 
                

                return View("UserDetails", user);
                
            }
            return View();
        }

        [HttpGet]
        public IActionResult UserDetails ()
        {
            ViewBag.Message = TempData["Message"];
            return View();
        }
        public async Task<IActionResult> Download(Guid id)
        {
            var filename = await _context.docUploads.Where(x => x.DocUploadId == id).FirstOrDefaultAsync();
            if (filename == null)
                return Content("filename not present");
            string webrootPath = _hostEnvironment.WebRootPath;
            var uploads = Path.Combine(webrootPath, "images");

            var path = Path.Combine(
                           Directory.GetCurrentDirectory(),
                           uploads, filename.FileName);

            var memory = new MemoryStream();
            using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }
            memory.Position = 0;
            return File(memory,_unitOfWork.GetContentType(path), Path.GetFileName(path));
        }



    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DevDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DevDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DevDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_uploadPartial.cshtml
@model DevDemo.ViewModels.UserInfoViewModel

<h4>UserInfoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="FileUpload" asp-controller="UserInfo" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserFiles"></label>
                <input type="file" multiple class="form-control-file" asp-for="UserFiles">
                <span asp-validation-for="UserFiles" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserInfo/GetUser.cshtml
@model DevDemo.ViewModels.UserSearchViewModel

@{
    ViewData["Title"] = "GetUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />
<section class="container" style="width: 700px;">
    <form asp-action="GetUser" asp-controller="UserInfo" method="post" class="form jumbotron">
        <div class="form-row form-group">

            <div class="col-md-12">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="TransNum" class="control-label"></label>
                <input asp-for="TransNum" class="form-control" />
                <span asp-validation-for="TransNum" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row form-group">
            <div class="col-md-12">
                <input type="submit" value="Submit" id="btn" class="btn btn-danger btn-block form-control">
            </div>
        </div>
        
    </form>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserInfo/UserDetails.cshtml
@model IEnumerable<DevDemo.Models.UserInfo>

@{
    ViewData["Title"] = "GetUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="alert alert-success alert-dismissible" style="margin-top:20px">
    @ViewBag.Message
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.TransNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fileUploads)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.TransNumber)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>

                    @if (Model.Any())
                    {

                        @foreach (var doc in item.fileUploads)
                        {
                            <div>
                    <img src="~/images/@doc.FileName" style="width: 18rem;" height="50"asp-append-version="true" alt="@doc.FileName"   > 
                           </div>                                                        
                            <div>
                                <a asp-action="Download" asp-route-id="@doc.DocUploadId" target="_top" class="btn btn-success">Download</a>
                            </div>
                        }

                    }
                </td>
               
            </tr>
        }
    </tbody>
</table>

Views/UserInfo/UserUpload.cshtml
@model DevDemo.ViewModels.UserInfoViewModel

@{
    ViewData["Title"] = "UserUpload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />

<section class="container" style="width: 700px;">
    <form asp-action="UserUpload" asp-controller="UserInfo" enctype="multipart/form-data" method="post" class="form jumbotron">
        <div class="form-row form-group">
            <div class="col-md-12">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
                <span class="FirstNameinfo"></span>
            </div>

            <div class="col-md-12">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row form-group">
            <div class="col-md-12">
                <label asp-for="Address" class="control-label"></label>
                <textarea asp-for="Address" class="form-control"></textarea>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="col-md-6">
                <label asp-for="UserFiles"></label>
                <input type="file" multiple class="form-control-file-label" asp-for="UserFiles">
                <span asp-validation-for="UserFiles" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row form-group">
            <div class="col-md-12">
                <input type="submit" value="Submit" id="btn" class="btn btn-danger btn-block form-control">
            </div>
        </div>
    </form>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}